import type { PanelConfig } from '../types';

/** Edit this array to add/remove journey panels — nothing else required */
export const PANELS: PanelConfig[] = [
  {
    id: 'explore',
    title: 'Explore Halifax',
    logbookEntry: 'Day 1, 06:00 — Departed Dartmouth ferry, fog lifting...',
    waypoint: 'I',
    marginNote: 'Fair winds. The ferry horn still in my ears.',
    description: 'Morning clear. Drop anchor where the harbour meets the Atlantic.',
    illustration: 'coastal',
    popLabel: 'Chart pin — Halifax harbour',
    routeCenterX: 250,
    midProp: 'gull',
    sceneProp2: 'buoy',
    sceneProp3: 'ripple',
    midPropPositions: {
      primary: 'left-[12%] bottom-[18%] w-16 md:w-20',
      secondary: 'left-[38%] bottom-0 w-14 md:w-16',
      tertiary: 'left-[52%] bottom-[1%] w-20 md:w-24',
    },
    sceneAccent: 'dawn-mist',
    layout: {
      chartLeft: '6%',
      chartRotate: '-1.5deg',
      illuLeft: '14%',
      illuBottom: '26%',
      illuScale: '1.08',
      cardRight: '4%',
    },
    weather: 'clear-morning',
    bgGradient: 'linear-gradient(165deg, rgba(13,148,136,0.22) 0%, #0c2340 52%, #06101a 100%)',
    cardVariant: 'log',
    parallaxBg: -50,
    parallaxFg: -120,
    sponsorHarbour: false,
  },
  {
    id: 'build',
    title: 'Build & Ship',
    logbookEntry: 'Day 1, 14:00 — Overcast. The crew found their rhythm.',
    waypoint: 'II',
    marginNote: 'Rain on the deck — good code weather.',
    description: 'Workshops, mentors, and long watches — ship through the weather.',
    illustration: 'rocket',
    popLabel: 'Tools ready — ship it',
    routeCenterX: 1150,
    midProp: 'rope',
    sceneProp2: 'buoy',
    sceneProp3: 'dory',
    midPropPositions: {
      primary: 'left-[16%] bottom-[16%] w-14 md:w-16 rotate-[-8deg]',
      secondary: 'left-[42%] bottom-0 w-12 md:w-14',
      tertiary: 'left-[58%] bottom-[2%] w-16 md:w-20',
    },
    sceneAccent: 'workshop-squall',
    layout: {
      chartLeft: '6%',
      chartRotate: '1deg',
      illuLeft: '11%',
      illuBottom: '20%',
      illuScale: '1.02',
      cardRight: '4%',
    },
    weather: 'focused-overcast',
    bgGradient: 'linear-gradient(165deg, #1e3a5f 0%, #0c2340 62%, #06101a 100%)',
    cardVariant: 'workshop',
    parallaxBg: -50,
    parallaxFg: -120,
    sponsorHarbour: false,
  },
  {
    id: 'sponsors',
    title: 'The Harbour',
    logbookEntry: 'Day 2, 08:00 — Six ships at anchor. Good people aboard each.',
    waypoint: 'III',
    marginNote: 'Six hulls at the wharf — each flying a kind flag.',
    description: 'Flagships · Navigators · Crew — moored and ready.',
    illustration: 'harbour',
    popLabel: 'Partners at anchor',
    routeCenterX: 2500,
    midProp: 'buoy',
    sceneProp2: 'rope',
    sceneProp3: 'sail',
    midPropPositions: {
      primary: 'left-[6%] bottom-[6%] w-12 md:w-14',
      secondary: 'left-[78%] bottom-[8%] w-10 md:w-12 rotate-[6deg]',
      tertiary: 'left-[88%] bottom-[14%] w-12 md:w-14 opacity-60',
    },
    sceneAccent: 'golden-harbour',
    layout: {
      chartLeft: '6%',
      chartRotate: '-1deg',
      illuLeft: '16%',
      illuBottom: '28%',
      illuScale: '1.12',
      cardRight: '4%',
    },
    weather: 'golden-hour',
    bgGradient: 'linear-gradient(165deg, rgba(227,160,8,0.28) 0%, #0c2340 48%, #06101a 100%)',
    cardVariant: 'harbour',
    parallaxBg: -50,
    parallaxFg: -120,
    sponsorHarbour: true,
    hideChart: true,
  },
  {
    id: 'crew',
    title: 'Join the Crew',
    logbookEntry: 'Day 2, 22:00 — Lanterns lit. The pier is waiting.',
    waypoint: 'IV',
    marginNote: 'Sign before the ink dries. The gangway is open.',
    description: 'Pack your laptop. The pier awaits.',
    illustration: 'anchor',
    popLabel: 'Sign before the ink dries',
    routeCenterX: 3500,
    midProp: 'gull',
    sceneProp2: 'trap',
    sceneProp3: 'kelp',
    midPropPositions: {
      primary: 'left-[10%] bottom-[20%] w-16 md:w-20',
      secondary: 'left-[40%] bottom-0 w-12 md:w-14',
      tertiary: 'left-[56%] bottom-[4%] w-10 md:w-12 rotate-[6deg]',
    },
    sceneAccent: 'lantern-gangway',
    layout: {
      chartLeft: '6%',
      chartRotate: '-2deg',
      illuLeft: '12%',
      illuBottom: '24%',
      illuScale: '1.06',
      cardRight: '4%',
    },
    weather: 'lantern-dusk',
    bgGradient: 'linear-gradient(165deg, rgba(153,45,34,0.35) 0%, #0c2340 50%, #06101a 100%)',
    cardVariant: 'gangway',
    parallaxBg: -50,
    parallaxFg: -120,
    sponsorHarbour: false,
  },
];

/** Shared voyage route path (4000 × 120 viewBox) — horizontal at y=60 */
export const VOYAGE_ROUTE_D =
  'M60,60 L500,60 L1500,60 L2500,60 L3500,60 L3940,60';

/** Route endpoints in viewBox X — used to sync traveler % position with scroll */
export const VOYAGE_ROUTE_START_X = 60;
export const VOYAGE_ROUTE_END_X = 3940;
export const VOYAGE_ROUTE_VIEWBOX_W = 4000;
